language: cpp
dist: bionic
compiler: gcc
os: linux

script:
  - sudo apt-get update
  - sudo apt-get install -y python3-setuptools
  - sudo apt-get install -y python3-pip
  - sudo apt-get clean
  - pip3 install conan
  - mkdir -p build
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan install . -s build_type=Debug --install-folder=build --build=missing
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --target soundex_test -- -j $(nproc)
  - ctest -R soundex -j $(nproc)