language: cpp
dist: bionic
compiler: gcc
os: linux

script:
  - sudo apt-get update
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
  - pip3 install conan
  - mkdir -p build
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan install . -s build_type=Debug --install-folder=build --build=missing
  - chmod +x build.sh
  - ./build.sh