language: cpp
dist: bionic
compiler: gcc
os: linux

install:
  - sudo apt-get update
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
  - pip3 install conan
  - mkdir -p build
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan install . -s build_type=Debug --install-folder=build --build=missing

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --target all --config Debug -- -j $(nproc)
  - cmake --build . --target soundex_test -- -j $(nproc)
  - ctest -j $(nproc)